# Generated by Django 5.0.6 on 2024-07-09 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consortium", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Secretariat",
            fields=[
                ("secretariat_id", models.AutoField(primary_key=True, serialize=False)),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("mname", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(max_length=100)),
                ("email_add", models.CharField(max_length=100)),
                ("contact_no", models.CharField(max_length=20)),
                ("date_appointed", models.DateField(blank=True, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        choices=[("Female", "Female"), ("Male", "Male")],
                        default="Female",
                        max_length=10,
                    ),
                ),
                (
                    "organization",
                    models.CharField(
                        choices=[
                            ("DOST-PCAARD", "DOST-PCAARD"),
                            ("Consortium", "Consortium"),
                        ],
                        default="Consortium",
                        max_length=11,
                    ),
                ),
                ("bach_deg", models.CharField(blank=True, max_length=100, null=True)),
                ("bdyearcompleted", models.IntegerField(blank=True, null=True)),
                ("mas_deg", models.CharField(blank=True, max_length=100, null=True)),
                ("mdyearcompleted", models.IntegerField(blank=True, null=True)),
                ("doc_deg", models.CharField(blank=True, max_length=100, null=True)),
                ("ddyearcompleted", models.IntegerField(blank=True, null=True)),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="secretariat_photo/"
                    ),
                ),
                (
                    "pds_file",
                    models.FileField(
                        blank=True, null=True, upload_to="secretariat_pds/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "consortium_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="consortium.consortium",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subordinates",
                        to="secretariat.secretariat",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "secretariat",
            },
        ),
    ]
