from django.urls import path, include
from . import views
from cmscore.views import *
from .views import consortium_data

urlpatterns = [
    path('', index, name = 'index'),
    path('dashcmi/', dashcmi, name='dashcmi'),
    path('dashslider/', dashslider, name='dashslider'),
    path('dashfaq/', dashfaq, name='dashfaq'),
    path('dashcommodity/', dashcommodity, name='dashcommodity'),
    path('dashcommunity/', dashcommunity, name='dashcommunity'),
    path('dashproject/', dashproject, name='dashproject'),
    path('dashservices/', dashservices, name='dashservices'),
    path('dashuser/', dashuser, name='dashuser'),
    path('maps/', map, name='map'),
    path('map/', views.map_endpoint, name='map_endpoint'),
    path('slider/', dashslider, name='slider'),
    path('contact/', contact, name='contact'),
    path('about/', about, name='about'),
    path('community/', community, name='community'),
    path('allpost/', allpost, name='allpost'),
    path('mypost/', mypost, name='mypost'),
    path('postsection/', postman, name='postman'),
    path('postcreateview/', createpost, name='postcreateview'),
    path('mypost/<slug:slug>/update/', updatepost, name='post_update'),
    path('deletecomment/<int:id>/', commentsdel, name='commentdelete'),
    path('deleteuser/<int:id>/', deleteuser, name='deleteuser'),
    path('deletepost/<slug:slug>/', deletepost, name='deletepost'),
    path('deletepostuser/<slug:slug>/', deletepostuser, name='deletepostuser'),
    path('deletecategory/<slug:slug>/', deletecategory, name='deletecategory'),
    path('commodities/', commodities, name='commodities'),
    path('commodetail/<int:com_id>/', views.commodetail, name='commodetail'),
    path('services/', services, name='services'),
    path('contentcreate/', ContentCreate.as_view(), name = 'contentcreate'),
    path('contentdelete/<int:id>/', contentdelete, name='contentdelete'),
    path('dashcontent/', dashcontent, name = 'dashcontent'),
    path('aboutus/', aboutus, name = 'aboutus'),
    path('manual/', manual, name = 'manual'),
    path('createloginbg/', loginbgcreate, name='createloginbg'),
    path('loginbgupdate/<int:pk>/', LoginbgUpdate.as_view(), name='loginbgupdate'),
    path('cmi-data/', cmi_data_view, name='cmi_data'),
    path('cmi/', cmi, name='cmi'),
    path('cmi/<int:cmi_id>/', cmi_detail, name='cmi'),
    path('search/', views.search, name='search'),
    path('Dashboard/',CMIadmin, name='CMIadmin'),
    path('contactus/',contactus, name='contactus'),
    path('slides/', view_slide, name='view_slide'),
    path('slides/add/', add_slide, name='add_slide'),
    path('slides/<int:slide_id>/edit/', edit_slide, name='edit_slide'),
    path('slides/<int:slide_id>/delete/', delete_slide, name='delete_slide'),
    path('api/project-status-count/', project_status_count, name='project_status_count'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)