# Generated by Django 5.2.3 on 2025-06-13 02:31

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_propertynum', models.CharField(max_length=50, verbose_name='Property Number')),
                ('item_name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('item_desc', models.CharField(max_length=50, verbose_name='Item Description')),
                ('item_purdate', models.DateField(verbose_name='Purchase Date')),
                ('po_number', models.CharField(max_length=50, verbose_name='PO Number')),
                ('fund_source', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fund Source')),
                ('supplier', models.CharField(max_length=100, verbose_name='Supplier')),
                ('item_amount', models.FloatField(verbose_name='Item Amount')),
                ('assigned_to', models.CharField(max_length=100, verbose_name='Assigned To')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('end_user', models.CharField(max_length=100, verbose_name='End User')),
                ('cat_id', models.IntegerField(verbose_name='Category ID')),
                ('status_id', models.IntegerField(default=4, verbose_name='Status ID')),
                ('created_at', models.DateField(default=datetime.datetime.now, verbose_name='Created')),
                ('updated_at', models.DateField(default=datetime.datetime.now, verbose_name='Updated')),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment Records',
            },
        ),
    ]
