# Generated by Django 5.2.3 on 2025-06-13 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='cat_id',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='item_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='equipments.category', verbose_name='Category'),
        ),
    ]
