# Generated by Django 5.2.3 on 2025-06-13 04:41

import equipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_status_remove_equipment_status_id_equipment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='user_image',
            field=models.ImageField(default='Equipment_pic/image.jpg', upload_to=equipments.models.image_path, verbose_name='Equipment Image'),
        ),
    ]
