# Generated by Django 5.2.3 on 2025-06-27 05:14

import equipments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_alter_status_options_equipment_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='additional_info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Additional Info'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Current Location'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='user_image',
            field=models.ImageField(default='equipment_pic/default.jpg', upload_to=equipments.models.image_path, verbose_name='Equipment Image'),
        ),
    ]
