# Generated by Django 5.2.3 on 2025-06-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_equipment_created_by_equipment_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='assigned_to',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='end_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='End User'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Supplier'),
        ),
    ]
