# Generated by Django 5.2.3 on 2025-06-29 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_alter_equipment_assigned_to_alter_equipment_end_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='additional_info',
            field=models.CharField(default='No additional info', max_length=300, verbose_name='Additional Info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='end_user',
            field=models.CharField(default='No additional info', max_length=100, verbose_name='End User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='item_desc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Description'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='item_purdate',
            field=models.DateField(blank=True, null=True, verbose_name='Purchase Date'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(default='No additional info', max_length=100, verbose_name='Location'),
            preserve_default=False,
        ),
    ]
