# Generated by Django 5.2.3 on 2025-06-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_alter_equipment_additional_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='additional_info',
            field=models.CharField(max_length=1000, verbose_name='Additional Info'),
        ),
    ]
