# Generated by Django 5.2.3 on 2025-07-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_alter_equipment_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipment',
            name='return_document',
            field=models.FileField(blank=True, null=True, upload_to='return_docs/', verbose_name='Return Document'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='additional_info',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Additional Info'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='end_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='End User'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PO Number'),
        ),
    ]
