# Generated by Django 5.2.3 on 2025-07-01 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_equipment_is_returned_equipment_return_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_equipments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='return_condition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Condition Upon Return'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='return_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Return Remarks'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='return_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Return Type'),
        ),
    ]
