# Generated by Django 5.2.3 on 2025-07-02 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0011_equipment_received_by_equipment_return_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='returned_by',
            field=models.CharField(blank=True, max_length=100, verbose_name='Returned By'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='received_by',
            field=models.CharField(blank=True, default=1, max_length=100, verbose_name='Received By'),
            preserve_default=False,
        ),
    ]
