# Generated by Django 5.2.3 on 2025-07-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0013_alter_equipment_received_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='order_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
