# Generated by Django 5.2.3 on 2025-07-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0014_equipment_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
