# Generated by Django 5.2.3 on 2025-07-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0017_equipmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenthistory',
            name='new_assigned_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipmenthistory',
            name='new_end_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
