# Generated by Django 5.2.3 on 2025-07-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0020_remove_equipmenthistory_new_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='item_propertynum',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Property Number'),
        ),
    ]
