# Generated by Django 5.2.3 on 2025-07-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0023_returndocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentactionlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('edit', 'Edited'), ('delete', 'Deleted'), ('archive', 'Archived'), ('unarchive', 'Unarchived'), ('return', 'Returned'), ('reissue', 'Reissued')], max_length=20),
        ),
    ]
