# Generated by Django 5.2.3 on 2025-07-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0024_alter_equipmentactionlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='damage_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Damage Reason'),
        ),
    ]
