# Generated by Django 5.2.4 on 2025-08-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0026_equipment_lost_remarks_replacementdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='assignment_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Assignment Change Reason'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_location_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Current Location Change Reason'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='location_change_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Location Change Reason'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='user_change_reason',
            field=models.TextField(blank=True, null=True, verbose_name='End User Change Reason'),
        ),
    ]
