# Generated by Django 5.2.4 on 2025-08-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0027_equipment_assignment_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmenthistory',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Change Reason'),
        ),
    ]
