# Generated by Django 5.2.4 on 2026-02-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0030_seed_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total Value'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='units',
            field=models.IntegerField(default=1, verbose_name='Units/Quantity'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='item_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price'),
        ),
    ]
