# Generated by Django 5.0.6 on 2024-07-08 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consortium',
            fields=[
                ('consortium_id', models.AutoField(primary_key=True, serialize=False)),
                ('consortium_code', models.CharField(max_length=50)),
                ('consortium_name', models.CharField(max_length=255)),
                ('consortium_address', models.CharField(max_length=255)),
                ('geolat', models.FloatField(blank=True, null=True)),
                ('geolong', models.FloatField(blank=True, null=True)),
                ('consortium_logo', models.ImageField(upload_to='consortium_logos/')),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('consortium_desc', models.TextField(blank=True, null=True)),
                ('consortium_objectives', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('fb_url', models.URLField(blank=True, max_length=255, null=True)),
                ('yt_url', models.URLField(blank=True, max_length=255, null=True)),
                ('telno', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consortium',
            },
        ),
        migrations.CreateModel(
            name='CMI',
            fields=[
                ('agency_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('is_cmi', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=255)),
                ('geolat', models.FloatField(blank=True, null=True)),
                ('geolong', models.FloatField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='cmi_logos/')),
                ('detail', models.TextField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=70, null=True)),
                ('telno', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('consortium_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.consortium')),
            ],
            options={
                'db_table': 'cmi',
            },
        ),
    ]
