# Generated by Django 5.0.6 on 2024-07-08 12:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodity', '0001_initial'),
        ('consortium', '0001_initial'),
        ('program', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('proj_id', models.IntegerField(blank=True, db_index=True)),
                ('title', models.CharField(max_length=250)),
                ('daterequestedext', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proj_leader', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='program.researcher', verbose_name='Project Leader')),
            ],
            options={
                'verbose_name': 'historical project',
                'verbose_name_plural': 'historical projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PriorityArea',
            fields=[
                ('priority_id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'priority_area',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('proj_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('proj_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=100)),
                ('proj_type', models.CharField(choices=[('R&D', 'R&D'), ('Non-R&D', 'Non-R&D')], default='R&D', max_length=20, verbose_name='Project Type')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('final_impl_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('approved_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('daterequestedext', models.DateField(blank=True, null=True)),
                ('ext_duration', models.IntegerField(blank=True, null=True)),
                ('proj_file', models.FileField(blank=True, null=True, upload_to='project_files/')),
                ('date_uploaded', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('co_impl_agency', models.ManyToManyField(blank=True, related_name='project_co_impl_agency', to='consortium.cmi')),
                ('commodity', models.ManyToManyField(blank=True, related_name='proj_com', to='commodity.commodity', verbose_name='Commodity')),
                ('coop_agency', models.ManyToManyField(blank=True, related_name='coop_agency', to='consortium.cmi')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fund_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='consortium.cmi')),
                ('impl_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='consortium.cmi')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.priorityarea')),
                ('prog_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proj_prog', to='program.program')),
                ('proj_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_leader', to='program.researcher', verbose_name='Project Leader')),
                ('proj_stakeholder', models.ManyToManyField(blank=True, related_name='stakeholder', to='program.stakeholder')),
                ('proj_team', models.ManyToManyField(blank=True, related_name='team', to='program.researcher')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='program.researcher')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='ProjectImplementingSite',
            fields=[
                ('projimp', models.AutoField(primary_key=True, serialize=False)),
                ('barangay', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=5, null=True)),
                ('geolat', models.FloatField(blank=True, null=True)),
                ('geolong', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_imp', to='project.project')),
            ],
            options={
                'db_table': 'proj_imp_site',
            },
        ),
        migrations.CreateModel(
            name='ProjectOutput',
            fields=[
                ('projout_id', models.AutoField(primary_key=True, serialize=False)),
                ('proj_output_type', models.CharField(choices=[('Publication', 'Publication'), ('Patent', 'Patent'), ('Property', 'Property'), ('Product', 'Product'), ('People', 'People'), ('Place and Partnership', 'Place and Partnership')], default='Publication', max_length=100)),
                ('proj_output_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('iec_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='commodity.iecmaterial')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proj_output', to='project.project')),
            ],
            options={
                'db_table': 'proj_output',
            },
        ),
        migrations.CreateModel(
            name='Sdg',
            fields=[
                ('sdg_no', models.AutoField(primary_key=True, serialize=False)),
                ('sdg_title', models.CharField(max_length=100)),
                ('sdg_desc', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sdg',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sdg_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='project.sdg'),
        ),
    ]
