# Generated by Django 5.0.6 on 2024-08-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="remarks",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="remarks",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
