from django.contrib import admin
from django.urls import path
from auth_user.views import (registration, login, logout_view, accountman, edit_user, delete_user, change_password, reset_password)
from cmscore.views import *
from cmsblg.views import (posts, detail, AllPosts, MyPosts, create_post, delete_post, view_posts, add_post, edit_post, delete_post, add_fact,
                            edit_fact, delete_fact, add_category, edit_category, delete_category, delete_comment, edit_comment, delete_postcms)
from commodity.views import (commodities, commodity_detail, view_commodity, add_commodity, edit_commodity, delete_commodity
                                ,view_IEC ,add_IEC, edit_IEC,delete_IEC)
from secretariat.views import secretariatview, add_secretariat, delete_secretariat, edit_secretariat, secretariat_hierarchy
from team.views import (add_team, view_team, edit_team, delete_team)
from project.views import (project, onproject, finproject, project_detail,
                            project_view, add_project, edit_project,
                            delete_project, view_sdg, add_sdg, edit_sdg, delete_sdg,
                            priority_area_view, add_priority_area, edit_priority_area, delete_priority_area, view_project_outputs,
                             add_project_output, edit_project_output, delete_project_output, view_project_implementing_sites, add_project_implementing_site,
                             edit_project_implementing_site, delete_project_implementing_site, generate_project_report)
from program.views import (program, program_detail, program_View, add_view, edit_program, delete_program, View_researcher,
                            add_researcher, edit_researcher, delete_researcher, View_stakeholders, add_stakeholders,
                            edit_stakeholders, delete_stakeholders, view_program_budget, add_program_budget, edit_program_budget,
                            delete_program_budget, generate_pdf_report )
from consortium.views import CMI_View, add_CMI, edit_Consortium, edit_CMI, delete_CMI, generate_cmi_report
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view, name="index"),
    path('registration/', registration, name= "registration"),
    path('login/', login, name='login'),
    path('logout/', logout_view, name="logout"),
    path('cmi/', cmi, name="cmi"),
    path('commodities/', commodities, name="commodity"),
    path('projects/', project, name="project"),
    path('On-GoingProjects/', onproject, name="onproject"),
    path('CompletedProjects/', finproject, name="finproject"),
    path('community/', community, name='community'),
    path('FAQs/', FaQ, name="faqs"),
    path('Consortium/', consortium, name="consortium"),
    path('Organization/', organization, name="organization"),
    path('cmi-data/', cmi_data_view, name='cmi_data'),
    path('cmi/<int:cmi_id>/', cmi_detail, name='cmi'),
    path('commodities/<int:com_id>/', commodity_detail, name='commodetail'),
    path('project/<int:proj_id>/', project_detail, name='project_detail'),
    path('posts/<slug:cat>/', posts, name='posts'),
    path('Details/<slug:category_slug>/<slug:slug>/', detail, name='detail'),
    path('Programs/', program, name='program'),
    path('programs/<prog_id>/',program_detail, name='program_details'),
    path('All_Posts/', AllPosts, name='allposts'),
    path('my_posts/', MyPosts, name='myposts'),
    path('New_Posts/', create_post, name ='newposts'),
    path('delete_post/<int:pk>/', delete_postcms, name='delete_postcms'),
    path('search/', search, name='search'),
    path('Profiling/',CMIadmin, name='CMIadmin'),
    path('contactus/',contactus, name='contactus'),
    path('accounts/', accountman, name='accountman'),
    path('edit_user/<int:user_id>/', edit_user, name='edit_user'),
    path('delete_user/<int:user_id>/', delete_user, name='delete_user'),
    path('change_password/', change_password, name='change_password'),
    path('reset_password/<int:user_id>/', reset_password, name='reset_password'),
    path('secretariat/', secretariatview, name= 'secretariatview'),
    path('add_secretariat/', add_secretariat, name='add_secretariat'),
    path('delete_secretariat/<int:secretariat_id>/', delete_secretariat, name='delete_secretariat'),
    path('edit_secretariat/<int:secretariat_id>/', edit_secretariat, name='edit_secretariat'),
    path('secretariat_hierarchy/', secretariat_hierarchy, name='secretariat_hierarchy'),
    path('CMI_view/', CMI_View, name='CMI_View'),
    path('add_CMI/', add_CMI, name='add_CMI'),
    path('report/cmi/<int:agency_id>/', generate_cmi_report, name='cmi_report'),
    path('edit_consortium/<int:consortium_id>', edit_Consortium, name='edit_Consortium'),
    path('edit_CMI/<int:agency_id>/', edit_CMI, name='edit_CMI'),
    path('delete_CMI/<int:agency_id>/', delete_CMI, name='delete_CMI'),
    path('Cluster/',view_team,name='view_team'),
    path('Add_member/',add_team,name='add_team'),
    path('Edit_member/<int:member_id>/',edit_team, name='edit_team'),
    path('Delete_member/<int:member_id>/', delete_team, name='delete_team'),
    path('View_Programs/', program_View, name='program_View'),
    path('Add_program/', add_view, name ='add_program'),
    path('Edit_program/<int:prog_id>', edit_program, name ='edit_program'),
    path('Delete_program/<int:prog_id>', delete_program, name ='delete_program'),
    path('View_projects/', project_view, name = 'project_view'),
    path('Add_projects/', add_project, name = 'add_project'),
    path('Edit_projects/<int:proj_id>', edit_project, name = 'edit_project'),
    path('Delete_projects/<int:proj_id>', delete_project, name = 'delete_project'),
    path('View_Commodity/', view_commodity, name = "view_commodity"),
    path('Add_Commodity/', add_commodity, name = "add_commodity"),
    path('Edit_Commodity/<int:com_id>', edit_commodity, name = "edit_commodity"),
    path('Delete_Commodity/<int:com_id>', delete_commodity, name = "delete_commodity"),
    path('View_sdg/', view_sdg, name='view_sdg'),
    path('Add_sdg/', add_sdg, name='add_sdg'),
    path('Edit_sdg/<int:sdg_no>', edit_sdg, name='edit_sdg'),
    path('Delete_sdg/<int:sdg_no>', delete_sdg, name='delete_sdg'),
    path('View_researcher/', View_researcher, name= 'View_researcher'),
    path('Add_researcher/', add_researcher, name='add_researcher'),
    path('Edit_researcher/<int:researcher_id>', edit_researcher, name='edit_researcher'),
    path('Delete_researcher/<int:researcher_id>', delete_researcher, name='delete_researcher'),
    path('View_IEC/', view_IEC, name = 'view_IEC'),
    path('Add_IEC/', add_IEC, name = 'add_IEC'),
    path('Edit_IEC/<int:iec_id>', edit_IEC, name='edit_IEC'),
    path('Delete_IEC/<int:iec_id>', delete_IEC, name='delete_IEC'),
    path('View_stakeholders/', View_stakeholders, name= 'View_stakeholders'),
    path('Add_stakeholders/', add_stakeholders, name='add_stakeholders'),
    path('Edit_stakeholders/<int:stakeholder_id>', edit_stakeholders, name='edit_stakeholders'),
    path('Delete_stakeholders/<int:stakeholder_id>', delete_stakeholders, name='delete_stakeholders'),
    path('priority_areas/', priority_area_view, name='view_priority_areas'),
    path('priority_areas/create/', add_priority_area, name='add_priority_area'),
    path('priority_areas/<int:priority_area_id>/edit/', edit_priority_area, name='edit_priority_area'),
    path('priority_areas/<int:priority_area_id>/delete/', delete_priority_area, name='delete_priority_area'),
    path('View_Program_Budget/', view_program_budget, name= 'view_program_budget'),
    path('Add_Program_Budget/', add_program_budget, name='add_program_budget'),
    path('Edit_Program_Budget/<int:progbdg_id>', edit_program_budget, name='edit_program_budget'),
    path('Delete_Program_Budget/<int:progbdg_id>', delete_program_budget, name='delete_program_budget'),
    path('project_outputs/', view_project_outputs, name='view_project_outputs'),
    path('project_outputs/add/', add_project_output, name='add_project_output'),
    path('project_outputs/<int:projout_id>/edit/', edit_project_output, name='edit_project_output'),
    path('project_outputs/<int:projout_id>/delete/', delete_project_output, name='delete_project_output'),
    path('project_implementing_sites/', view_project_implementing_sites, name='view_project_implementing_sites'),
    path('project_implementing_sites/add/', add_project_implementing_site, name='add_project_implementing_site'),
    path('project_implementing_sites/<int:site_id>/edit/', edit_project_implementing_site, name='edit_project_implementing_site'),
    path('project_implementing_sites/<int:site_id>/delete/', delete_project_implementing_site, name='delete_project_implementing_site'),
    path('slides/', view_slide, name='view_slide'),
    path('slides/add/', add_slide, name='add_slide'),
    path('slides/<int:slide_id>/edit/', edit_slide, name='edit_slide'),
    path('slides/<int:slide_id>/delete/', delete_slide, name='delete_slide'),
    path('View_posts/', view_posts, name= 'view_posts'),
    path('Add_Post/', add_post, name='add_post'),
    path('Edit_Post/<int:post_id>', edit_post, name='edit_post'),
    path('Delete_Post/<int:post_id>', delete_post, name='delete_post'),
    path('Add_Fact/', add_fact, name='add_fact'),
    path('Edit_Fact/<int:fact_id>', edit_fact, name='edit_fact'),
    path('Delete_Fact/<int:fact_id>', delete_fact, name='delete_fact'),
    path('Add_Category/', add_category, name='add_category'),
    path('Edit_Category/<int:category_id>', edit_category, name='edit_category'),
    path('Delete_Category/<int:category_id>', delete_category, name='delete_category'),
    path('report/program/<int:program_id>/', generate_pdf_report, name='generate_pdf_report'),
    path('report/project/<int:proj_id>/', generate_project_report, name='generate_project_report'),
    path('api/project-status-count/', project_status_count, name='project_status_count'),
    path('api/program-status-count/', program_status_count, name='program_status_count'),
    path('api/project-count-per-year/', project_count_per_year_api, name='project_count_per_year_api'),
    path('api/projects-per-year/', projects_per_year_data, name='projects_per_year_data'),
    path('api/cmi-status-count/', cmi_status_count, name='cmi_status_count'),
    path('comment/delete/<int:comment_id>/', delete_comment, name='delete_comment'),
    path('comment/<int:comment_id>/edit/', edit_comment, name='edit_comment'),
    path('activity-management/', activity_management, name='activity_management')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)